repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      #-   id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/drewbernetes/pre-commits.git
    rev: v0.1.0
    hooks:
      - id: trivy
        args:
          - fs
          - .
